### ISSUE TITLE
Class is wrong

### ISSUE THREAD

**Issue by amwalding** [jmillana/ip_calculator#1]
There is a problem with how pycidr states the "Class" of the address.
Only the first bits of the first byte determine the class, not the mask.
![2023-12-09_10-23-20](https://github.com/jmillana/pycidr/assets/37885145/dfed3097-c813-4e40-9b7e-e8958b377205)

So for example in the supernet show in the screenshot, this is still a class B as the first three bits are 0 0 1.

**Comment by amwalding** [comment]
Sorry - I meant Class C

**Comment by jmillana** [comment]
@amwalding thanks for reporting the error, indeed the CIDR class calculation method was wrong, a new release will be out today fixing the error

**Comment by jmillana** [comment]
Fixed on 431c3fd786665fab59dd1c4e13aa865e20997296
Version 0.1.1 has been released with the fix
